project_id = "amdutxcbbzvafwyghrll"

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.request-signature]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-signature-link]
verify_jwt = false

[functions.send-etapa-summary]
verify_jwt = false

[functions.sign-etapa]
verify_jwt = false